name: Bug Report
description: File a bug report to help us improve k6-reporter
title: '[Bug]: '
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us identify and fix the issue.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: false

  - type: input
    id: k6-version
    attributes:
      label: k6 Version
      description: What version of k6 are you running? Check with `k6 --version`
      placeholder: 'e.g., v1.3.0'
    validations:
      required: true

  - type: input
    id: k6-reporter-version
    attributes:
      label: k6-reporter Version
      description: What version of k6-reporter are you using?
      placeholder: 'e.g., v3.0.1 or commit hash if using from source'
    validations:
      required: true

  - type: textarea
    id: k6-script-sample
    attributes:
      label: Sample k6 Script
      description: If applicable, provide a minimal k6 script that reproduces the issue
      render: javascript
      placeholder: |
        import { htmlReport } from 'https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js';

        export function handleSummary(data) {
          return {
            "summary.html": htmlReport(data),
          };
        }

        export default function () {
          // Your test code here
        }

  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: If applicable, provide any error messages or logs
      render: shell
      placeholder: Paste any error messages or relevant log output here
